import worker, { upstreamFor, allowedOrigin } from "./src/index.js";
const env = { ALLOWED_ORIGINS: "https://mikecostarella.github.io,http://localhost:*", FINNHUB_KEY: "fh-secret" };
const calls = [];
globalThis.fetch = async (url, init) => {
  calls.push({ url, method: init.method, headers: Object.fromEntries(init.headers.entries()), body: init.body ? await new Response(init.body).text() : undefined });
  return new Response(JSON.stringify({ echoed: true }), { status: 200, headers: { "Content-Type": "application/json", "X-RateLimit-Remaining": "199", "Set-Cookie": "leak=1" } });
};
const req = (path, opts = {}) => new Request("https://relay.example" + path, { headers: { Origin: "https://mikecostarella.github.io", ...(opts.headers || {}) }, method: opts.method || "GET", body: opts.body });
const results = {};
let r = await worker.fetch(req("/api/trading/v2/account", { method: "OPTIONS" }), env);
results.preflight = [r.status, r.headers.get("Access-Control-Allow-Headers")];
r = await worker.fetch(req("/api/trading/v2/account"), env);
results.noKeys = [r.status, (await r.json()).message.slice(0, 15)];
r = await worker.fetch(req("/api/trading/v2/orders", { method: "POST", headers: { "X-Alpaca-Key-Id": "PK1", "X-Alpaca-Secret-Key": "S1", "Content-Type": "application/json" }, body: JSON.stringify({ symbol: "AAPL" }) }), env);
const c = calls.at(-1);
results.forward = [r.status, c.url, c.method, c.headers["apca-api-key-id"], c.headers["apca-api-secret-key"], c.body, r.headers.get("Access-Control-Allow-Origin"), r.headers.get("Set-Cookie"), r.headers.get("X-RateLimit-Remaining")];
r = await worker.fetch(req("/api/data/v2/stocks/snapshots?symbols=SPY,QQQ&feed=iex", { headers: { "X-Alpaca-Key-Id": "PK1", "X-Alpaca-Secret-Key": "S1" } }), env);
results.dataQuery = calls.at(-1).url;
r = await worker.fetch(req("/api/fundamentals/stock/profile2?symbol=AAPL"), env);
results.finnhub = [r.status, calls.at(-1).url, calls.at(-1).headers["x-finnhub-token"]];
r = await worker.fetch(req("/api/fundamentals/stock/profile2?symbol=AAPL"), { ...env, FINNHUB_KEY: "" });
results.finnhubOff = r.status;
r = await worker.fetch(new Request("https://relay.example/api/trading/v2/account", { headers: { Origin: "https://evil.example", "X-Alpaca-Key-Id": "PK1", "X-Alpaca-Secret-Key": "S1" } }), env);
results.badOrigin = r.status;
r = await worker.fetch(new Request("https://relay.example/api/trading/v2/account", { headers: { Origin: "http://localhost:5175", "X-Alpaca-Key-Id": "PK1", "X-Alpaca-Secret-Key": "S1" } }), env);
results.localhost = [r.status, r.headers.get("Access-Control-Allow-Origin")];
r = await worker.fetch(req("/api/nope"), env);
results.unknown = r.status;
r = await worker.fetch(new Request("https://relay.example/health"), env);
results.health = [r.status, await r.json()];
results.liveNeverReached = calls.every((x) => !x.url.includes("api.alpaca.markets") || x.url.includes("paper-api"));
console.log(JSON.stringify(results, null, 1));
